exercise_html_purifier:
    default_cache_serializer_path: '%kernel.cache_dir%/htmlpurifier'
    html_profiles:
        full:
            config:
                HTML.Trusted: true
                Core.Encoding: 'UTF-8'
                HTML.Doctype: 'XHTML 1.0 Transitional'
                HTML.DefinitionID: 'enduser-customize.html ninjatooken'
                HTML.DefinitionRev: 1
                HTML.Allowed: 'h3[style|align],h4[style|align],h5[style|align],h6[style|align],p[style|align],span[style],ul,li[style],a[href|target],strong,b,em,i,u,strike,br,img[src|width|height|alt|align],legend,fieldset,object[width|height|codebase|classid],param[name|value],embed[type|width|height|src],iframe[frameborder|marginheight|marginwidth|scrolling|src|height|width],font[face|size|color]'
                HTML.TargetBlank: true
                AutoFormat.Linkify: true
                CSS.AllowedProperties:  'text-decoration,text-align,color,font,font-family,font-size,font-style,font-weight,float,clear'
                HTML.SafeObject: true
                HTML.SafeEmbed: true
                Output.FlashCompat: true
                HTML.FlashAllowFullScreen: true
                URI.DisableExternalResources: false
                Core.RemoveInvalidImg: true
                URI.Base: 'http://www.ninjatooken.fr'
                URI.MakeAbsolute: true
        medium:
            config:
                Core.Encoding: 'UTF-8'
                HTML.Allowed: 'p,span,li,strong,b,em,i,strike,br,'
                HTML.TargetBlank: true
                CSS.AllowedProperties:  'color,font,font-weight'
        min:
            config:
                Core.Encoding: 'UTF-8'
                HTML.Allowed: 'p,strong,b,em,i,strike,'
                AutoFormat.RemoveEmpty: true
                AutoFormat.RemoveEmpty.RemoveNbsp : true
                CSS.AllowedProperties:  'color,font,font-weight'