fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User\User
    group:
        group_class: App\Entity\User\Group
        group_manager: sonata.user.orm.group_manager
    from_email:
        address: "%mail_contact%"
        sender_name: "%mail_name%"
    service:
        mailer: fos_user.mailer.twig_swift
        user_manager: sonata.user.orm.user_manager
    resetting:
        form:
            type: ninjatooken_user_resetting
        email:
            from_email:
                address: "%mail_contact%"
                sender_name: "%mail_name%"
            template: user/resetting.email.html.twig
    registration:
        form:
            type: App\Form\Type\RegistrationFormType

        confirmation:
            from_email:
                address: "%mail_contact%"
                sender_name: "%mail_name%"
            template: user/confirmation.email.html.twig
            enabled: false