framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        # so we can connect from unity
        cookie_samesite: 'lax'
        cookie_secure: auto
        cookie_domain: ".%base_host%"
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    router:
        utf8: true

    translator:      { fallback: "%locale%" }
    form:            ~
    default_locale:  "%locale%"