# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "cache"
    filter_sets :
        cache : ~
        avatar:
            quality : 75
            filters :
                thumbnail  : { size : [100, 100], mode : outbound }
        kamon:
            quality : 75
            filters :
                thumbnail  : { size : [250, 250], mode : outbound }