sonata_admin:
  security:
    handler: sonata.admin.security.handler.role
  title: DaFuckingAdmin
  title_logo: /bundles/sonataadmin/logo_title.png
  options:
    html5_validate: false
    confirm_exit: false
    use_select2: false
  dashboard:
    blocks:
      - position: left
        type: sonata.admin.block.admin_list
      - position: right
        type: sonata.block.service.text
        settings:
          content: >-
            <div class='alert alert-block'><h4>Sonata Admin</h4> <p>Attentions :
            toutes les actions de suppressions et de modifications sont
            définitives.</p></div>
      - position: right
        type: block.recent_comments
        settings:
          title: Commentaires récents
          number: 10
          mode: admin
    groups:
      user:
        label: Utilisateurs
      clan:
        label: Clans
      forum:
        label: Forums
  assets:
      stylesheets:
          - bundles/sonataadmin/app.css
      extra_stylesheets: []
      remove_stylesheets: []
      javascripts:
          - bundles/sonataadmin/app.js
      extra_javascripts: []
      remove_javascripts: []
sonata_block:
  default_contexts:
    - cms
  blocks:
    sonata.admin.block.admin_list:
      contexts:
        - admin
    sonata.block.service.text: null
    sonata.block.service.action: null
    sonata.block.service.rss: null
    block.recent_comments: null
sonata_doctrine_orm_admin:
    entity_manager: ~
    audit:
        force: true
    templates:
        types:
            list:
                array:      "@SonataAdmin/CRUD/list_array.html.twig"
                boolean:    "@SonataAdmin/CRUD/list_boolean.html.twig"
                date:       "@SonataAdmin/CRUD/list_date.html.twig"
                time:       "@SonataAdmin/CRUD/list_time.html.twig"
                datetime:   "@SonataAdmin/CRUD/list_datetime.html.twig"
                text:       "@SonataAdmin/CRUD/base_list_field.html.twig"
                trans:      "@SonataAdmin/CRUD/list_trans.html.twig"
                string:     "@SonataAdmin/CRUD/base_list_field.html.twig"
                smallint:   "@SonataAdmin/CRUD/base_list_field.html.twig"
                bigint:     "@SonataAdmin/CRUD/base_list_field.html.twig"
                integer:    "@SonataAdmin/CRUD/base_list_field.html.twig"
                decimal:    "@SonataAdmin/CRUD/base_list_field.html.twig"
                identifier: "@SonataAdmin/CRUD/base_list_field.html.twig"
                currency:   "@SonataAdmin/CRUD/list_currency.html.twig"
                percent:    "@SonataAdmin/CRUD/list_percent.html.twig"
                choice:     "@SonataAdmin/CRUD/list_choice.html.twig"
                url:        "@SonataAdmin/CRUD/list_url.html.twig"

            show:
                array:      "@SonataAdmin/CRUD/show_array.html.twig"
                boolean:    "@SonataAdmin/CRUD/show_boolean.html.twig"
                date:       "@SonataAdmin/CRUD/show_date.html.twig"
                time:       "@SonataAdmin/CRUD/show_time.html.twig"
                datetime:   "@SonataAdmin/CRUD/show_datetime.html.twig"
                text:       "@SonataAdmin/CRUD/base_show_field.html.twig"
                trans:      "@SonataAdmin/CRUD/show_trans.html.twig"
                string:     "@SonataAdmin/CRUD/base_show_field.html.twig"
                smallint:   "@SonataAdmin/CRUD/base_show_field.html.twig"
                bigint:     "@SonataAdmin/CRUD/base_show_field.html.twig"
                integer:    "@SonataAdmin/CRUD/base_show_field.html.twig"
                decimal:    "@SonataAdmin/CRUD/base_show_field.html.twig"
                currency:   "@SonataAdmin/CRUD/base_currency.html.twig"
                percent:    "@SonataAdmin/CRUD/base_percent.html.twig"
                choice:     "@SonataAdmin/CRUD/show_choice.html.twig"
                url:        "@SonataAdmin/CRUD/show_url.html.twig"