ninja_tooken_chat_homepage:
    path:  /{_locale}/chat/
    controller: App\Controller\ChatController::index
    requirements:
        _locale: en|fr
    defaults:
        _locale: fr

ninja_tooken_chat_ajax:
    path:  /chat/ajax/
    controller: App\Controller\ChatController::ajax
