ninja_tooken_homepage:
    path:  /
    controller: App\Controller\CommonController::index

ninja_tooken_jouer:
    path:  /jouer
    controller: App\Controller\CommonController::jouer

ninja_tooken_manuel:
    path:  /guide-du-ninja
    controller: App\Controller\CommonController::manuel

ninja_tooken_reglement:
    path:  /regles-respecter
    controller: App\Controller\CommonController::reglement

ninja_tooken_chat:
    path:  /chat
    controller: App\Controller\CommonController::chat

ninja_tooken_faq_generale:
    path:  /faq-generale
    controller: App\Controller\CommonController::faqGenerale

ninja_tooken_faq_technique:
    path:  /faq-technique
    controller: App\Controller\CommonController::faqTechnique

ninja_tooken_team:
    path:  /team
    controller: App\Controller\CommonController::team

ninja_tooken_mentions_legales:
    path:  /mentions-legales
    controller: App\Controller\CommonController::mentionsLegales

ninja_tooken_contact:
    path:  /nous-contacter
    controller: App\Controller\CommonController::contact

ninja_tooken_search:
    path:  /search
    controller: App\Controller\CommonController::search

