ninja_tooken_game_parties:
    path:  /parties-en-cours
    controller: App\Controller\GameController::parties

ninja_tooken_game_calculateur:
    path:  /calculateur-jutsus
    controller: App\Controller\GameController::calculateur

ninja_tooken_game_classement:
    path:  /classement/{page}
    controller: App\Controller\GameController::classement
    defaults:
        page: 1
    requirements:
        page:  \d*