root:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /%locale%/
        permanent: true

add_blocker:
    path: /adimages/
    controller: App\Controller\CommonController::addBlocker

ninja_tooken_chat:
    resource: "chat.yaml"
    prefix:   /{_locale}/
    requirements:
        _locale: en|fr
    defaults:
        _locale: fr

ninja_tooken_common:
    resource: "common.yaml"
    prefix:   /{_locale}/
    requirements:
        _locale: en|fr
    defaults:
        _locale: fr

ninja_tooken_clan:
    resource: "clan.yaml"
    prefix:   /{_locale}/
    requirements:
        _locale: en|fr
    defaults:
        _locale: fr

ninja_tooken_game:
    resource: "game.yaml"
    prefix:   /{_locale}/
    requirements:
        _locale: en|fr
    defaults:
        _locale: fr

ninja_tooken_game_unity:
    resource: "unity.yaml"
    prefix:   /

ninja_tooken_forum:
    resource: "forum.yaml"
    prefix:   /{_locale}/
    requirements:
        _locale: en|fr
    defaults:
        _locale: fr

ninja_tooken_user:
    resource: "user.yaml"
    prefix:   /{_locale}/
    requirements:
        _locale: en|fr
    defaults:
        _locale: fr