admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /{_locale}/daFuckingAdmin
    requirements:
        _locale: en|fr
    defaults:
        _locale: fr

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /{_locale}/daFuckingAdmin
    requirements:
        _locale: en|fr
    defaults:
        _locale: fr
