ninja_tooken_game_unity_update:
    path:  /bundles/ninjatookengame/xml/game/update.php
    controller: App\Controller\UnityController:::update

ninja_tooken_game_unity_connect:
    path:  /bundles/ninjatookengame/xml/game/connect.php
    controller: App\Controller\UnityController:::connect