ninja_tooken_user_resetting_request:
    path: /request
    controller: App\Controller\ResetPasswordController::request
    methods: [GET, POST]

ninja_tooken_user_resetting_check_email:
    path: /check-email
    controller: App\Controller\ResetPasswordController::checkEmail
    methods: [GET]

ninja_tooken_user_resetting_reset:
    path: /reset/{token?}
    controller: App\Controller\ResetPasswordController::reset
    methods: [GET, POST]